"""Create accounting_entries and audit_log_entries tables

Revision ID: 8186db494d34
Revises: 
Create Date: 2025-12-10 10:42:07.542162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8186db494d34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('recorder_id', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('proof_attachment_link', sa.String(), nullable=True),
    sa.Column('pdf_unique_ref_number', sa.String(), nullable=True),
    sa.Column('gcs_pdf_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pdf_unique_ref_number')
    )
    op.create_index(op.f('ix_accounting_entries_id'), 'accounting_entries', ['id'], unique=False)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_entry_id', sa.Integer(), nullable=False),
    sa.Column('details_of_change', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['target_entry_id'], ['accounting_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_id'), 'audit_log_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entries_id'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index(op.f('ix_accounting_entries_id'), table_name='accounting_entries')
    op.drop_table('accounting_entries')
    # ### end Alembic commands ###
